Adding 2016 pre-VFP entries (v12)
uhh-cms/cmsdb pull request #21
Opened 2024-01-15 16:18 UTC by aalvesan

Adding the campaign run2_2016_HIPM_uhh_v12. Includes all cmsdb entries for data, signal and background for 2016 nanoAOD datasets, at version 12, and for pre-VFP era.

2024-01-24 17:14 UTC, pkausw requested changes
Hi @aalvesan , thanks for this massive amount of work! All in all, it looks in good shape :+1: I have some small requests:
- there are typos here and there in the different files. I did my best to check everything carefully, but can you also have another look?
- I think the imports in the different files point to the 2017 campaign, please correct this
- Therse seems to be an issue with datasets that or present twice. Might be connected to extenstions of datasets, which logically should belong to the dataset w/o the `ext` tag
- Can you also solve the linting errors on your branch?

I'm also tagging @dsavoiu here, because I know he also put some thought and work into the naming scheme of processes and datasets. Maybe he'll have additional comments

2024-01-24 17:14 UTC, pkausw commented on cmsdb/campaigns/run2_2016_HIPM_uhh_v12/hh2bbtautau.py
> +    processes=[procs.graviton_hh_vbf_bbtautau_m700_madgraph],
```suggestion
    processes=[procs.graviton_hh_vbf_bbtautau_m700],
```

2024-01-24 17:14 UTC, pkausw commented on cmsdb/campaigns/run2_2016_HIPM_uhh_v12/hh2bbtautau.py
> +    processes=[procs.graviton_hh_vbf_bbtautau_m1550],
```suggestion
    processes=[procs.graviton_hh_vbf_bbtautau_m1500],
```

2024-01-25 09:04 UTC, aalvesan commented on cmsdb/campaigns/run2_2016_HIPM_uhh_v12/Signals.py
> +# coding: utf-8
this was the wrong file, sorry.

2024-01-25 10:12 UTC, aalvesan commented on cmsdb/campaigns/run2_2016_HIPM_uhh_v12/MultiBoson.py
> +)
one should be zzz and the other zzz_ext, but I did zzz_ext twice.... I will fix it

2024-01-25 10:12 UTC, aalvesan commented on cmsdb/campaigns/run2_2016_HIPM_uhh_v12/MultiBoson.py
> +)
same mistake here

2024-01-25 10:50 UTC, aalvesan commented on cmsdb/campaigns/run2_2016_HIPM_uhh_v12/__init__.py
> +            "location": "davs://dcache-cms-webdav-wan.desy.de:2880/pnfs/desy.de/cms/tier2/store/user/bwieders/nano_uhh_v11/merged_2048.0MB",  # noqa
yes, I fixed it

2024-01-29 15:01 UTC, dsavoiu requested changes
Hi @aalvesan, thanks for adding this campaign! And thanks @pkausw for the ping ;)

I only noticed some minor things (naming conventions, typos), but maybe you could have a look and make changes where necessary?
 
Also, in general, I think it would be good to only use lowercase or "snake-case" for filenames in `cmsdb`, so instead of `MultiBoson.py`, could you use `multi_boson.py` or similar? Same for one-letter filenames (`Z.py` -> `z.py`, etc.)

Actually, I think in general in the other campaigns we collected the Drell-Yan, Multiboson, Z and W background samples in one electroweak file `ewk.py`. Unless we have a good reason for the separation, I would propose to rename or merge following files into one:
* `DY.py`, `MultiBoson.py`, `W.py`, `Z.py` -> `ewk.py`
* `SingleHiggs.py` -> `higgs.py`
* `SingleTop.py` -> `st.py`

2024-01-31 11:10 UTC, aalvesan commented on cmsdb/campaigns/run2_2016_HIPM_uhh_v12/MultiBoson.py
> +    processes=[procs.zzz_ext],
okay, I will include all of your suggestions. Thanks for the review! :)

2024-02-01 12:01 UTC, dsavoiu requested changes
Hi @aalvesan, thanks for implementing the changes! Everything looks fine now, I just noticed a few minor things that should be easy to fix (see below).

2024-02-22 12:33 UTC, dsavoiu commented
Hi @aalvesan, sorry for the delay in reviewing this. I actually noticed that I had overlooked some things in the initial review and also that the tests were failing due to some typos in the imports and missing processes. I took the liberty of committing a series of changes to fix these issues, so this should in principle now be ready to merge.

But @aalvesan please check if the changes work for you and I would also ping @riga and @pkausw here in case they also want to look over the changes before the merge.

2024-03-06 16:15 UTC, dsavoiu commented
Hi @aalvesan, I fixed the conflicts with the `master` branch, which were due to the restructuring of unit tests introduced by #22. Did you manage to have a look at the latest changes? If there are no further things to do we could go ahead and merge this soon.

2024-03-11 12:58 UTC, riga approved these changes
LGTM!

2024-03-11 13:28 UTC, dsavoiu approved these changes

2024-03-11 13:30 UTC, merged