Campaign/run3 2022 nano v12
uhh-cms/cmsdb pull request #24
Opened 2024-02-06 12:37 UTC by mafrahm

This PR adds campaigns for 2022 nano v12

Draft, since PR https://github.com/uhh-cms/cmsdb/pull/20 needs to be merged first

2024-02-27 08:56 UTC, mafrahm commented
This campaign implements some datasets containing extensions with a very large number of input files, e.g. this one: https://github.com/uhh-cms/cmsdb/blob/761843f118c992aec57141ca1260c1ceaf212520/cmsdb/campaigns/run3_2022_postEE_nano_v12/top.py#L28

Should we maybe think of a way to make it customizable whether to use such an extension or not? 
This might be helpful for prototyping an analysis where you need decent statistics but can probably spare the additional 50% of the stats.

2024-05-13 14:56 UTC, nprouvost requested changes
Add missing QCD processes

2024-05-16 16:03 UTC, nprouvost requested changes
review of 2022postEE

2024-05-17 07:06 UTC, mafrahm commented on cmsdb/campaigns/run3_2022_postEE_nano_v12/hh2bbww.py
> +# )
No, but let's do this in a separate PR

2024-05-17 07:11 UTC, mafrahm commented on cmsdb/campaigns/run3_2022_postEE_nano_v12/qcd.py
> +    name="qcd_em_pt300toInf_pythia",
I think the convention changes are a good idea, but maybe these should be handled in a single separate PR? I'd like to separate changes in existing processes/datasets from this PR, which only adds new datasets (and some new processes corresponding to datasets)

2024-05-17 07:30 UTC, mafrahm commented on cmsdb/campaigns/run3_2022_postEE_nano_v12/ewk.py
> +        "/DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM",  # noqa
I added it as an additional DatasetInfo

2024-05-17 11:12 UTC, nprouvost commented on cmsdb/campaigns/run3_2022_postEE_nano_v12/hh2bbww.py
> +# )
Since it's a new one I don't see the problem with doing it in this PR, you've already done that for QCD samples for examples, but works for me too

2024-05-17 11:14 UTC, nprouvost commented on cmsdb/campaigns/run3_2022_postEE_nano_v12/qcd.py
> +    name="qcd_em_pt300toInf_pythia",
fine by me

2024-05-17 11:15 UTC, nprouvost approved these changes

2024-05-17 11:17 UTC, nprouvost commented on cmsdb/campaigns/run3_2022_postEE_nano_v12/ewk.py
> +        "/DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM",  # noqa
lgtm

2024-05-17 11:51 UTC, merged