Adding JetHT data, ht-binned QCD and tt_fh samples to nano v9 2016/18 campaigns
uhh-cms/cmsdb pull request #69
Opened 2024-11-15 13:26 UTC by TomPD

This PR adds:

- run2_2016_nano_v9 and run2_2016_HIPM_nano_v9 campaigns
- JetHT data and ht-binned QCD for the nano v9 campaigns for 2016 and 2018
- tt_fh_powheg for nano v9 2016
- tt_fh mass variation samples to nano v9 2016/17/18

2025-04-15 13:09 UTC, TomPD commented
kind ping @riga

2025-04-15 15:48 UTC, riga requested changes
Hi @TomPD ,

this mostly looks good to me, but I had a couple inline comments that you can find below. In summary, I'd suggest two changes:

- Could you prepend "mt" to the top mass values in the ttbar datasets you added? This would follow the convention we started with (e.g.) adding "ht" for QCD or DY bins.
- It appears that the ttbar datasets for 2018 ended up in the campaign definition file. I guess it should be pretty straight forward to move them into a "top.py" file and load it in the campaign.


Besides that, I think we can go ahead and merge.

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2016_HIPM_nano_v9/data.py
> +
```suggestion

#
# JetHT
#

```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2016_nano_v9/top.py
> +    name="tt_fh_166p5_powheg",
```suggestion
    name="tt_fh_mt166p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2016_nano_v9/top.py
> +    name="tt_fh_169p5_powheg",
```suggestion
    name="tt_fh_mt169p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2016_nano_v9/top.py
> +    name="tt_fh_171p5_powheg",
```suggestion
    name="tt_fh_mt171p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2016_nano_v9/top.py
> +    name="tt_fh_173p5_powheg",
```suggestion
    name="tt_fh_mt173p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2016_nano_v9/top.py
> +    name="tt_fh_175p5_powheg",
```suggestion
    name="tt_fh_mt175p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2016_nano_v9/top.py
> +    name="tt_fh_178p5_powheg",
```suggestion
    name="tt_fh_mt178p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2017_nano_v9/top.py
> +    name="tt_fh_166p5_powheg",
```suggestion
    name="tt_fh_mt166p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2017_nano_v9/top.py
> +    name="tt_fh_169p5_powheg",
```suggestion
    name="tt_fh_mt169p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2017_nano_v9/top.py
> +    name="tt_fh_171p5_powheg",
```suggestion
    name="tt_fh_mt171p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2017_nano_v9/top.py
> +    name="tt_fh_173p5_powheg",
```suggestion
    name="tt_fh_mt173p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2017_nano_v9/top.py
> +    name="tt_fh_175p5_powheg",
```suggestion
    name="tt_fh_mt175p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2017_nano_v9/top.py
> +    name="tt_fh_178p5_powheg",
```suggestion
    name="tt_fh_mt178p5_powheg",
```

2025-04-15 15:48 UTC, riga commented on cmsdb/campaigns/run2_2018_nano_v9/__init__.py
> +
Could you move the following datasets to a file `top.py`?
Also, please prepend `mt` to the top mass values in dataset names.

2025-04-16 12:14 UTC, riga approved these changes
Thanks, looking good now :+1:

2025-04-16 12:14 UTC, merged